name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - "@tunahanertekin"
  - "@esgungor"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report and contributing robolaunch.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: What is the bug?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Select version of the project.
      options:
        - 1.0.0
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should be the normal output?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Give us the log output, it's auto-formatted to codeview.
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Drop the screenshots to help us understand the context if available.
      placeholder: Drag and drop your images.
    validations:
      required: false
  - type: textarea
    id: fix
    attributes:
      label: Fixing the Bug
      description: What could fix the bug?
      placeholder: Any tips?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/robolaunch/robolaunch/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true