# syntax=docker/dockerfile:1

#Build stage
FROM golang:1.17-buster AS build

WORKDIR /app

COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download

COPY ./launch/server ./launch/server
COPY ./launch/pkg ./launch/pkg
COPY ./api ./api


RUN cd launch/server;go build -o /server

#Deployable image
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /server /server

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/server"]