name: robolaunch

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker Registery
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Launch Service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfiles/Dockerfile-launch-server
          push: true
          tags: robolaunchio/launch-server:v${{ github.run_number }}, robolaunchio/launch-server:latest
      - name: Build Launch Worker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfiles/Dockerfile-worker
          push: true
          labels: robolaunchio/launch-worker
          tags: robolaunchio/launch-worker:v${{ github.run_number }}, robolaunchio/launch-worker:latest
